package net.zlt.create_vibrant_vaults;

import com.simibubi.create.foundation.data.AssetLookup;
import com.simibubi.create.foundation.data.SharedProperties;
import com.tterrag.registrate.util.entry.BlockEntry;
import io.github.fabricators_of_create.porting_lib.models.generators.ConfiguredModel;
import net.minecraft.core.Direction;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.material.MapColor;

import static com.simibubi.create.foundation.data.CreateRegistrate.connectedTextures;
import static com.simibubi.create.foundation.data.TagGen.pickaxeOnly;

public class AllBlocks {
    public static final BlockEntry<BlackItemVaultBlock> BLACK_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("black_item_vault", BlackItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.BLACK)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(BlackItemVaultCTBehaviour::new))
        .item(BlackItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<BlueItemVaultBlock> BLUE_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("blue_item_vault", BlueItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.BLUE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(BlueItemVaultCTBehaviour::new))
        .item(BlueItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<BrownItemVaultBlock> BROWN_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("brown_item_vault", BrownItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.BROWN)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(BrownItemVaultCTBehaviour::new))
        .item(BrownItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<CyanItemVaultBlock> CYAN_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("cyan_item_vault", CyanItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.CYAN)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(CyanItemVaultCTBehaviour::new))
        .item(CyanItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<GrayItemVaultBlock> GRAY_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("gray_item_vault", GrayItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.GRAY)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(GrayItemVaultCTBehaviour::new))
        .item(GrayItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<GreenItemVaultBlock> GREEN_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("green_item_vault", GreenItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.GREEN)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(GreenItemVaultCTBehaviour::new))
        .item(GreenItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<LightBlueItemVaultBlock> LIGHT_BLUE_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("light_blue_item_vault", LightBlueItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.LIGHT_BLUE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(LightBlueItemVaultCTBehaviour::new))
        .item(LightBlueItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<LightGrayItemVaultBlock> LIGHT_GRAY_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("light_gray_item_vault", LightGrayItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.LIGHT_GRAY)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(LightGrayItemVaultCTBehaviour::new))
        .item(LightGrayItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<LimeItemVaultBlock> LIME_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("lime_item_vault", LimeItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.LIME)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(LimeItemVaultCTBehaviour::new))
        .item(LimeItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<MagentaItemVaultBlock> MAGENTA_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("magenta_item_vault", MagentaItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.MAGENTA)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(MagentaItemVaultCTBehaviour::new))
        .item(MagentaItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<OrangeItemVaultBlock> ORANGE_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("orange_item_vault", OrangeItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.ORANGE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(OrangeItemVaultCTBehaviour::new))
        .item(OrangeItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<PinkItemVaultBlock> PINK_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("pink_item_vault", PinkItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.PINK)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(PinkItemVaultCTBehaviour::new))
        .item(PinkItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<PurpleItemVaultBlock> PURPLE_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("purple_item_vault", PurpleItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.PURPLE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(PurpleItemVaultCTBehaviour::new))
        .item(PurpleItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<RedItemVaultBlock> RED_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("red_item_vault", RedItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.RED)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(RedItemVaultCTBehaviour::new))
        .item(RedItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<WhiteItemVaultBlock> WHITE_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("white_item_vault", WhiteItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.WHITE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(WhiteItemVaultCTBehaviour::new))
        .item(WhiteItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<YellowItemVaultBlock> YELLOW_ITEM_VAULT = CreateVibrantVaults.REGISTRATE.block("yellow_item_vault", YellowItemVaultBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.YELLOW)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(YellowItemVaultCTBehaviour::new))
        .item(YellowItemVaultItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<ShippingContainerBlock> SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("shipping_container", ShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(MapColor.TERRACOTTA_BLUE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(ShippingContainerCTBehaviour::new))
        .item(ShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<BlackShippingContainerBlock> BLACK_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("black_shipping_container", BlackShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.BLACK)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(BlackShippingContainerCTBehaviour::new))
        .item(BlackShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<BlueShippingContainerBlock> BLUE_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("blue_shipping_container", BlueShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.BLUE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(BlueShippingContainerCTBehaviour::new))
        .item(BlueShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<BrownShippingContainerBlock> BROWN_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("brown_shipping_container", BrownShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.BROWN)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(BrownShippingContainerCTBehaviour::new))
        .item(BrownShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<CyanShippingContainerBlock> CYAN_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("cyan_shipping_container", CyanShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.CYAN)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(CyanShippingContainerCTBehaviour::new))
        .item(CyanShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<GrayShippingContainerBlock> GRAY_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("gray_shipping_container", GrayShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.GRAY)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(GrayShippingContainerCTBehaviour::new))
        .item(GrayShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<GreenShippingContainerBlock> GREEN_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("green_shipping_container", GreenShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.GREEN)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(GreenShippingContainerCTBehaviour::new))
        .item(GreenShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<LightBlueShippingContainerBlock> LIGHT_BLUE_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("light_blue_shipping_container", LightBlueShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.LIGHT_BLUE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(LightBlueShippingContainerCTBehaviour::new))
        .item(LightBlueShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<LightGrayShippingContainerBlock> LIGHT_GRAY_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("light_gray_shipping_container", LightGrayShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.LIGHT_GRAY)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(LightGrayShippingContainerCTBehaviour::new))
        .item(LightGrayShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<LimeShippingContainerBlock> LIME_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("lime_shipping_container", LimeShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.LIME)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(LimeShippingContainerCTBehaviour::new))
        .item(LimeShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<MagentaShippingContainerBlock> MAGENTA_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("magenta_shipping_container", MagentaShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.MAGENTA)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(MagentaShippingContainerCTBehaviour::new))
        .item(MagentaShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<OrangeShippingContainerBlock> ORANGE_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("orange_shipping_container", OrangeShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.ORANGE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(OrangeShippingContainerCTBehaviour::new))
        .item(OrangeShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<PinkShippingContainerBlock> PINK_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("pink_shipping_container", PinkShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.PINK)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(PinkShippingContainerCTBehaviour::new))
        .item(PinkShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<PurpleShippingContainerBlock> PURPLE_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("purple_shipping_container", PurpleShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.PURPLE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(PurpleShippingContainerCTBehaviour::new))
        .item(PurpleShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<RedShippingContainerBlock> RED_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("red_shipping_container", RedShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.RED)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(RedShippingContainerCTBehaviour::new))
        .item(RedShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<WhiteShippingContainerBlock> WHITE_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("white_shipping_container", WhiteShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.WHITE)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(WhiteShippingContainerCTBehaviour::new))
        .item(WhiteShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static final BlockEntry<YellowShippingContainerBlock> YELLOW_SHIPPING_CONTAINER = CreateVibrantVaults.REGISTRATE.block("yellow_shipping_container", YellowShippingContainerBlock::new)
        .initialProperties(SharedProperties::softMetal)
        .properties(p -> p.mapColor(DyeColor.YELLOW)
            .sound(SoundType.NETHERITE_BLOCK)
            .explosionResistance(1200))
        .transform(pickaxeOnly())
        .blockstate((c, p) -> p.getVariantBuilder(c.get())
            .forAllStates(s -> ConfiguredModel.builder()
                .modelFile(AssetLookup.standardModel(c, p))
                .rotationY(s.getValue(AbstractItemVaultBlock.HORIZONTAL_AXIS) == Direction.Axis.X ? 90 : 0)
                .build()))
        .onRegister(connectedTextures(YellowShippingContainerCTBehaviour::new))
        .item(YellowShippingContainerItem::new)
        .tab(AllCreativeModeTabs.BASE_CREATIVE_TAB.key())
        .build()
        .register();

    public static void register() {}
}
